Ultralytics 8.3.218  Python-3.11.13 torch-2.8.0+cpu CPU (13th Gen Intel Core i7-13700H)
[34m[1mengine\trainer: [0magnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=dataset\aquarium_dataset\data.yaml, degrees=0.0, deterministic=True, device=cpu, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=20, erasing=0.4, exist_ok=True, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=run_1761053325, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=yolo_streamlit, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=C:\Users\ghofr\Bureau\yolo_training\yolo_streamlit\run_1761053325, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Traceback (most recent call last):
  File "C:\Users\ghofr\anaconda3\envs\anaconda-ml-ai\Lib\site-packages\ultralytics\engine\trainer.py", line 645, in get_dataset
    data = check_det_dataset(self.args.data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ghofr\anaconda3\envs\anaconda-ml-ai\Lib\site-packages\ultralytics\data\utils.py", line 468, in check_det_dataset
    raise FileNotFoundError(m)
FileNotFoundError: Dataset 'dataset/aquarium_dataset/data.yaml' images not found, missing path 'C:\Users\ghofr\Bureau\yolo_training\dataset\aquarium_dataset\aquarium_dataset\images\val'
Note dataset download directory is 'C:\Users\datasets'. You can update this in 'C:\Users\ghofr\AppData\Roaming\Ultralytics\settings.json'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ghofr\Bureau\yolo_training\train_yolo.py", line 96, in <module>
    main()
  File "C:\Users\ghofr\Bureau\yolo_training\train_yolo.py", line 38, in main
    model.train(data=args.data, epochs=args.epochs, imgsz=args.imgsz,
  File "C:\Users\ghofr\anaconda3\envs\anaconda-ml-ai\Lib\site-packages\ultralytics\engine\model.py", line 795, in train
    self.trainer = (trainer or self._smart_load("trainer"))(overrides=args, _callbacks=self.callbacks)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ghofr\anaconda3\envs\anaconda-ml-ai\Lib\site-packages\ultralytics\models\yolo\detect\train.py", line 65, in __init__
    super().__init__(cfg, overrides, _callbacks)
  File "C:\Users\ghofr\anaconda3\envs\anaconda-ml-ai\Lib\site-packages\ultralytics\engine\trainer.py", line 158, in __init__
    self.data = self.get_dataset()
                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\ghofr\anaconda3\envs\anaconda-ml-ai\Lib\site-packages\ultralytics\engine\trainer.py", line 649, in get_dataset
    raise RuntimeError(emojis(f"Dataset '{clean_url(self.args.data)}' error ‚ùå {e}")) from e
RuntimeError: Dataset 'dataset/aquarium_dataset/data.yaml' error  Dataset 'dataset/aquarium_dataset/data.yaml' images not found, missing path 'C:\Users\ghofr\Bureau\yolo_training\dataset\aquarium_dataset\aquarium_dataset\images\val'
Note dataset download directory is 'C:\Users\datasets'. You can update this in 'C:\Users\ghofr\AppData\Roaming\Ultralytics\settings.json'
